version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chronotac-postgres
    restart: always
    environment:
      POSTGRES_DB: chronotac
      POSTGRES_USER: chronotac
      POSTGRES_PASSWORD: chronotac123
      POSTGRES_ROOT_PASSWORD: rootpwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chronotac-network

volumes:
  postgres_data:

networks:
  chronotac-network:
    driver: bridge