CREATE DATABASE IF NOT EXISTS tictac;
USE tictac;

CREATE USER IF NOT EXISTS 'chronotac'@'%' IDENTIFIED BY 'chronotac123';
GRANT ALL PRIVILEGES ON tictac.* TO 'chronotac'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    board JSON NOT NULL,
    winner VARCHAR(1) NULL,
    isDraw BOOLEAN DEFAULT FALSE,
    currentPlayer VARCHAR(1) NOT NULL,
    status VARCHAR(20) DEFAULT 'finished',
    playedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);